"""Unit and Integration Tests for Module 10: Alert Engine.

Covers all 30 required test areas:
1. Alert creation
2. Fence breach -> alert
3. Loitering -> alert
4. Severity mapping
5. Alert IDs
6. Active status
7. Duplicate event prevention
8. Different events produce separate alerts
9. Track isolation
10. Multiple simultaneous alerts
11. Get active alerts
12. Get alert by ID
13. Severity sorting
14. Type filtering
15. Acknowledge
16. Resolve
17. Invalid state transitions
18. Unknown alert ID
19. Reset
20. Clear
21. Alert immutability
22. Metadata preservation
23. Message generation
24. M8 -> M10 integration
25. M9 -> M10 integration
26. M8/M9 independence
27. No mutation of source events
28. Duplicate frame/event simulation
29. Alert counts/statistics
30. Realistic event sequence
"""

from dataclasses import FrozenInstanceError
from datetime import datetime, timedelta
import time
from typing import List

import pytest

from ai_engine.alerts import (
    Alert,
    AlertEngine,
    AlertError,
    AlertNotFoundError,
    AlertSeverity,
    AlertStatus,
    AlertType,
    AlertValidationError,
    DEFAULT_SEVERITY_MAPPING,
    InvalidAlertStateTransitionError,
    generate_fence_breach_message,
    generate_loitering_message,
)
from ai_engine.event_memory import EventMemory
from ai_engine.fence_breach import (
    BreachEventType,
    FenceBreachDetector,
    FenceBreachEvent,
    FenceState,
)
from ai_engine.loitering import (
    LoiteringDetector,
    LoiteringEvent,
    LoiteringState,
)
from ai_engine.tracker import TrackedObject
from ai_engine.zones import Zone, ZoneManager, ZoneType


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture
def alert_engine() -> AlertEngine:
    """Fixture providing a fresh AlertEngine instance."""
    return AlertEngine()


@pytest.fixture
def sample_fence_breach_event() -> FenceBreachEvent:
    """Fixture providing a standard M8 FenceBreachEvent."""
    return FenceBreachEvent(
        track_id=12,
        event_type=BreachEventType.FENCE_BREACH,
        previous_state=FenceState.OUTSIDE,
        current_state=FenceState.INSIDE,
        frame_id=45,
        timestamp=100.5,
        center=(320, 240),
        fence_id="fence_alpha",
        zone_id="zone_restricted_1",
        breach_count=1,
        metadata={"zone_name": "Perimeter North", "zone_type": "RESTRICTED"},
    )


@pytest.fixture
def sample_loitering_event() -> LoiteringEvent:
    """Fixture providing a standard M9 LoiteringEvent."""
    return LoiteringEvent(
        track_id=7,
        event_type="LOITERING",
        duration_seconds=32.5,
        spatial_displacement=15.2,
        spatial_radius=50.0,
        threshold_seconds=30.0,
        anchor_center=(200.0, 150.0),
        current_center=(205.0, 155.0),
        frame_id=980,
        timestamp=150.0,
        zone_id="zone_sensitive_2",
        zone_name="Warehouse Dock",
        zone_type="SENSITIVE",
        loitering_count=1,
    )


# ---------------------------------------------------------------------------
# Test Suite
# ---------------------------------------------------------------------------

class TestAlertEngineCreationAndStructure:
    """Tests 1, 5, 6, 21: Alert creation, IDs, active status, immutability."""

    def test_01_alert_creation_direct(self):
        """Test direct creation of an Alert record with valid attributes."""
        alert = Alert(
            alert_id="ALT-00001",
            track_id=1,
            alert_type=AlertType.FENCE_BREACH,
            severity=AlertSeverity.CRITICAL,
            status=AlertStatus.ACTIVE,
            timestamp=100.0,
            camera_id="cam_01",
            zone_id="z1",
            zone_name="Perimeter",
            zone_type="RESTRICTED",
            center=(100.0, 200.0),
            message="Test breach",
        )
        assert alert.alert_id == "ALT-00001"
        assert alert.track_id == 1
        assert alert.alert_type == AlertType.FENCE_BREACH
        assert alert.severity == AlertSeverity.CRITICAL
        assert alert.status == AlertStatus.ACTIVE
        assert alert.is_active is True
        assert alert.is_acknowledged is False
        assert alert.is_resolved is False
        assert alert.priority_rank == 4
        assert alert.center == (100.0, 200.0)

    def test_05_alert_ids_unique_and_monotonic(self, alert_engine: AlertEngine):
        """Test that alert IDs generated by engine are unique and monotonic."""
        e1 = FenceBreachEvent(track_id=1, breach_count=1, frame_id=1)
        e2 = FenceBreachEvent(track_id=2, breach_count=1, frame_id=1)
        e3 = FenceBreachEvent(track_id=3, breach_count=1, frame_id=1)

        a1 = alert_engine.process_fence_breach(e1)
        a2 = alert_engine.process_fence_breach(e2)
        a3 = alert_engine.process_fence_breach(e3)

        assert a1 is not None and a2 is not None and a3 is not None
        assert a1.alert_id == "ALT-00001"
        assert a2.alert_id == "ALT-00002"
        assert a3.alert_id == "ALT-00003"
        assert len({a1.alert_id, a2.alert_id, a3.alert_id}) == 3

    def test_06_new_alerts_have_active_status(
        self, alert_engine: AlertEngine, sample_fence_breach_event: FenceBreachEvent
    ):
        """Test that newly generated alerts default to ACTIVE status."""
        alert = alert_engine.process_fence_breach(sample_fence_breach_event)
        assert alert is not None
        assert alert.status == AlertStatus.ACTIVE
        assert alert.is_active is True
        assert alert.acknowledged_at is None
        assert alert.resolved_at is None

    def test_21_alert_immutability(self, sample_fence_breach_event: FenceBreachEvent):
        """Test that Alert records are frozen and reject in-place mutation."""
        alert = Alert(
            alert_id="ALT-TEST",
            track_id=1,
            alert_type=AlertType.FENCE_BREACH,
            severity=AlertSeverity.CRITICAL,
            status=AlertStatus.ACTIVE,
        )
        with pytest.raises(FrozenInstanceError):
            alert.status = AlertStatus.RESOLVED  # type: ignore

        with pytest.raises(FrozenInstanceError):
            alert.track_id = 99  # type: ignore


class TestEventConversionAndSeverity:
    """Tests 2, 3, 4, 22, 23: Event conversion, severity mapping, metadata, messages."""

    def test_02_fence_breach_to_alert(
        self, alert_engine: AlertEngine, sample_fence_breach_event: FenceBreachEvent
    ):
        """Test conversion of M8 FenceBreachEvent into Alert."""
        alert = alert_engine.process_fence_breach(sample_fence_breach_event, camera_id="cam_north")
        assert alert is not None
        assert alert.alert_type == AlertType.FENCE_BREACH
        assert alert.severity == AlertSeverity.CRITICAL
        assert alert.track_id == 12
        assert alert.camera_id == "cam_north"
        assert alert.zone_id == "zone_restricted_1"
        assert alert.zone_name == "Perimeter North"
        assert alert.zone_type == "RESTRICTED"
        assert alert.center == (320.0, 240.0)
        assert alert.source_event is sample_fence_breach_event

    def test_03_loitering_to_alert(
        self, alert_engine: AlertEngine, sample_loitering_event: LoiteringEvent
    ):
        """Test conversion of M9 LoiteringEvent into Alert."""
        alert = alert_engine.process_loitering(sample_loitering_event, camera_id="cam_dock")
        assert alert is not None
        assert alert.alert_type == AlertType.LOITERING
        assert alert.severity == AlertSeverity.HIGH
        assert alert.track_id == 7
        assert alert.camera_id == "cam_dock"
        assert alert.zone_name == "Warehouse Dock"
        assert alert.center == (205.0, 155.0)
        assert alert.source_event is sample_loitering_event

    def test_04_deterministic_and_configurable_severity(self):
        """Test default severity policy and configurable overrides."""
        # Default policy
        engine_default = AlertEngine()
        fb = FenceBreachEvent(track_id=1, breach_count=1)
        loiter = LoiteringEvent(track_id=2, loitering_count=1)

        a1 = engine_default.process_fence_breach(fb)
        a2 = engine_default.process_loitering(loiter)
        assert a1.severity == AlertSeverity.CRITICAL
        assert a2.severity == AlertSeverity.HIGH

        # Custom mapping via constructor
        custom_mapping = {
            AlertType.FENCE_BREACH: AlertSeverity.HIGH,
            AlertType.LOITERING: AlertSeverity.MEDIUM,
        }
        engine_custom = AlertEngine(severity_mapping=custom_mapping)
        a3 = engine_custom.process_fence_breach(fb)
        a4 = engine_custom.process_loitering(loiter)
        assert a3.severity == AlertSeverity.HIGH
        assert a4.severity == AlertSeverity.MEDIUM

        # Dynamic severity override via set_severity()
        engine_custom.set_severity(AlertType.LOITERING, AlertSeverity.LOW)
        loiter2 = LoiteringEvent(track_id=3, loitering_count=1)
        a5 = engine_custom.process_loitering(loiter2)
        assert a5.severity == AlertSeverity.LOW

    def test_22_metadata_preservation(
        self, alert_engine: AlertEngine, sample_fence_breach_event: FenceBreachEvent, sample_loitering_event: LoiteringEvent
    ):
        """Test that event metadata from M8 and M9 is fully preserved."""
        a1 = alert_engine.process_fence_breach(sample_fence_breach_event)
        assert a1.metadata["zone_name"] == "Perimeter North"
        assert a1.metadata["breach_count"] == 1
        assert a1.metadata["frame_id"] == 45
        assert a1.metadata["fence_id"] == "fence_alpha"

        a2 = alert_engine.process_loitering(sample_loitering_event)
        assert a2.metadata["duration_seconds"] == 32.5
        assert a2.metadata["spatial_displacement"] == 15.2
        assert a2.metadata["spatial_radius"] == 50.0
        assert a2.metadata["threshold_seconds"] == 30.0
        assert a2.metadata["loitering_count"] == 1
        assert a2.metadata["frame_id"] == 980
        assert a2.metadata["anchor_center"] == (200.0, 150.0)

    def test_23_human_readable_message_generation(self):
        """Test dynamic human-readable alert message generation from event metadata."""
        msg1 = generate_fence_breach_message(track_id=12, zone_name="Perimeter North")
        assert "Track 12" in msg1
        assert "Perimeter North" in msg1

        msg2 = generate_fence_breach_message(track_id=5, zone_type="RESTRICTED")
        assert "Track 5" in msg2
        assert "restricted perimeter" in msg2

        msg3 = generate_fence_breach_message(track_id=8)
        assert "Track 8" in msg3
        assert "virtual perimeter fence" in msg3

        msg4 = generate_loitering_message(track_id=7, duration_seconds=30.2, zone_name="Sensitive Area")
        assert "Track 7" in msg4
        assert "Sensitive Area" in msg4
        assert "30.2s" in msg4

        msg5 = generate_loitering_message(track_id=9, duration_seconds=0.0)
        assert "Track 9" in msg5
        assert "prolonged duration" in msg5


class TestDeduplicationAndIsolation:
    """Tests 7, 8, 9, 10, 28: Duplicate protection, track isolation, multi-alerts."""

    def test_07_duplicate_event_prevention_same_event(
        self, alert_engine: AlertEngine, sample_fence_breach_event: FenceBreachEvent
    ):
        """Test that passing the exact same event object again returns None."""
        alert1 = alert_engine.process_fence_breach(sample_fence_breach_event)
        assert alert1 is not None

        # Re-process identical event object
        alert2 = alert_engine.process_fence_breach(sample_fence_breach_event)
        assert alert2 is None
        assert len(alert_engine) == 1

    def test_07b_duplicate_event_prevention_equivalent_event(self, alert_engine: AlertEngine):
        """Test that distinct event objects with the same dedup key return None."""
        e1 = FenceBreachEvent(track_id=5, breach_count=1, frame_id=100, fence_id="f1", zone_id="z1")
        e2 = FenceBreachEvent(track_id=5, breach_count=1, frame_id=100, fence_id="f1", zone_id="z1")

        a1 = alert_engine.process_fence_breach(e1)
        a2 = alert_engine.process_fence_breach(e2)
        assert a1 is not None
        assert a2 is None
        assert len(alert_engine) == 1

    def test_08_different_events_produce_separate_alerts(self, alert_engine: AlertEngine):
        """Test that re-entry with incremented breach count produces a new alert."""
        e1 = FenceBreachEvent(track_id=5, breach_count=1, frame_id=50)
        e2 = FenceBreachEvent(track_id=5, breach_count=2, frame_id=250)  # re-entry

        a1 = alert_engine.process_fence_breach(e1)
        a2 = alert_engine.process_fence_breach(e2)
        assert a1 is not None
        assert a2 is not None
        assert a1.alert_id != a2.alert_id
        assert len(alert_engine) == 2

    def test_09_track_isolation(self, alert_engine: AlertEngine):
        """Test that events for different tracks are strictly isolated."""
        e1 = FenceBreachEvent(track_id=101, breach_count=1, frame_id=20)
        e2 = FenceBreachEvent(track_id=102, breach_count=1, frame_id=20)

        a1 = alert_engine.process_fence_breach(e1)
        a2 = alert_engine.process_fence_breach(e2)
        assert a1 is not None and a2 is not None
        assert a1.track_id == 101
        assert a2.track_id == 102
        assert len(alert_engine) == 2

    def test_10_multiple_simultaneous_alerts(self, alert_engine: AlertEngine):
        """Test batch processing of multiple simultaneous security events."""
        e1 = FenceBreachEvent(track_id=1, breach_count=1)
        e2 = LoiteringEvent(track_id=2, loitering_count=1, duration_seconds=30.0)
        e3 = FenceBreachEvent(track_id=3, breach_count=1)

        alerts = alert_engine.process_events([e1, e2, e3])
        assert len(alerts) == 3
        assert alerts[0].alert_type == AlertType.FENCE_BREACH
        assert alerts[1].alert_type == AlertType.LOITERING
        assert alerts[2].alert_type == AlertType.FENCE_BREACH

    def test_28_duplicate_frame_event_simulation(self, alert_engine: AlertEngine):
        """Simulate video pipeline passing repeated events across 60 consecutive frames."""
        event = FenceBreachEvent(track_id=15, breach_count=1, frame_id=30)
        created_alerts = []
        for _ in range(60):
            res = alert_engine.process_fence_breach(event)
            if res is not None:
                created_alerts.append(res)

        # Must yield exactly 1 alert, not 60
        assert len(created_alerts) == 1
        assert len(alert_engine) == 1


class TestAlertQueryingAndPriority:
    """Tests 11, 12, 13, 14, 29: Queries, sorting, filtering, statistics."""

    def test_11_get_active_alerts(self, alert_engine: AlertEngine):
        """Test retrieving active alerts and excluding resolved alerts."""
        e1 = FenceBreachEvent(track_id=1, breach_count=1)
        e2 = LoiteringEvent(track_id=2, loitering_count=1)
        e3 = FenceBreachEvent(track_id=3, breach_count=1)

        a1 = alert_engine.process_fence_breach(e1)
        a2 = alert_engine.process_loitering(e2)
        a3 = alert_engine.process_fence_breach(e3)

        alert_engine.resolve(a2.alert_id)

        active = alert_engine.get_active_alerts()
        active_ids = [a.alert_id for a in active]
        assert a1.alert_id in active_ids
        assert a3.alert_id in active_ids
        assert a2.alert_id not in active_ids
        assert len(active) == 2

    def test_12_get_alert_by_id(self, alert_engine: AlertEngine):
        """Test retrieving alert by valid ID and handling nonexistent ID."""
        e1 = FenceBreachEvent(track_id=1, breach_count=1)
        a1 = alert_engine.process_fence_breach(e1)

        found = alert_engine.get_alert(a1.alert_id)
        assert found is not None
        assert found.alert_id == a1.alert_id

        not_found = alert_engine.get_alert("ALT-NONEXISTENT")
        assert not_found is None

    def test_13_severity_and_timestamp_priority_sorting(self, alert_engine: AlertEngine):
        """Test deterministic priority sorting: CRITICAL > HIGH > MEDIUM > LOW, then newest first."""
        # Create alerts with different severities and timestamps
        fb1 = FenceBreachEvent(track_id=1, breach_count=1, timestamp=10.0)  # CRITICAL, t=10
        fb2 = FenceBreachEvent(track_id=2, breach_count=1, timestamp=20.0)  # CRITICAL, t=20
        lt1 = LoiteringEvent(track_id=3, loitering_count=1, timestamp=30.0)  # HIGH, t=30
        lt2 = LoiteringEvent(track_id=4, loitering_count=1, timestamp=5.0)   # HIGH, t=5

        a_fb1 = alert_engine.process_fence_breach(fb1)
        a_fb2 = alert_engine.process_fence_breach(fb2)
        a_lt1 = alert_engine.process_loitering(lt1)
        a_lt2 = alert_engine.process_loitering(lt2)

        sorted_alerts = alert_engine.get_all_alerts(sort_by_priority=True)
        # Expected order:
        # 1. a_fb2 (CRITICAL, t=20)
        # 2. a_fb1 (CRITICAL, t=10)
        # 3. a_lt1 (HIGH, t=30)
        # 4. a_lt2 (HIGH, t=5)
        assert sorted_alerts[0].alert_id == a_fb2.alert_id
        assert sorted_alerts[1].alert_id == a_fb1.alert_id
        assert sorted_alerts[2].alert_id == a_lt1.alert_id
        assert sorted_alerts[3].alert_id == a_lt2.alert_id

    def test_14_type_and_criteria_filtering(self, alert_engine: AlertEngine):
        """Test filtering alerts by type, severity, status, track_id, zone_id."""
        e1 = FenceBreachEvent(track_id=10, breach_count=1, zone_id="z_alpha")
        e2 = LoiteringEvent(track_id=20, loitering_count=1, zone_id="z_beta")
        e3 = FenceBreachEvent(track_id=10, breach_count=2, zone_id="z_alpha")

        a1 = alert_engine.process_fence_breach(e1, camera_id="cam1")
        a2 = alert_engine.process_loitering(e2, camera_id="cam2")
        a3 = alert_engine.process_fence_breach(e3, camera_id="cam1")

        # Filter by type
        breaches = alert_engine.filter_alerts(alert_type=AlertType.FENCE_BREACH)
        assert len(breaches) == 2
        assert all(b.alert_type == AlertType.FENCE_BREACH for b in breaches)

        # Filter by track_id
        track_10_alerts = alert_engine.filter_alerts(track_id=10)
        assert len(track_10_alerts) == 2

        # Filter by camera_id
        cam2_alerts = alert_engine.filter_alerts(camera_id="cam2")
        assert len(cam2_alerts) == 1
        assert cam2_alerts[0].alert_id == a2.alert_id

    def test_29_alert_counts_and_statistics(self, alert_engine: AlertEngine):
        """Test statistics aggregations by severity, type, and status."""
        e1 = FenceBreachEvent(track_id=1, breach_count=1)
        e2 = FenceBreachEvent(track_id=2, breach_count=1)
        e3 = LoiteringEvent(track_id=3, loitering_count=1)

        a1 = alert_engine.process_fence_breach(e1)
        a2 = alert_engine.process_fence_breach(e2)
        a3 = alert_engine.process_loitering(e3)

        alert_engine.acknowledge(a1.alert_id)
        alert_engine.resolve(a2.alert_id)

        # Count active
        assert alert_engine.count_active_alerts(include_acknowledged=False) == 1
        assert alert_engine.count_active_alerts(include_acknowledged=True) == 2

        # Count by status
        status_counts = alert_engine.count_alerts_by_status()
        assert status_counts[AlertStatus.ACTIVE] == 1
        assert status_counts[AlertStatus.ACKNOWLEDGED] == 1
        assert status_counts[AlertStatus.RESOLVED] == 1

        # Count by type
        type_counts = alert_engine.count_alerts_by_type()
        assert type_counts[AlertType.FENCE_BREACH] == 2
        assert type_counts[AlertType.LOITERING] == 1

        # Count by severity
        sev_counts = alert_engine.count_alerts_by_severity()
        assert sev_counts[AlertSeverity.CRITICAL] == 2
        assert sev_counts[AlertSeverity.HIGH] == 1
        assert sev_counts[AlertSeverity.MEDIUM] == 0


class TestLifecycleAndStateTransitions:
    """Tests 15, 16, 17, 18, 19, 20: Acknowledge, resolve, invalid transitions, reset."""

    def test_15_acknowledge_transition(self, alert_engine: AlertEngine):
        """Test transitioning ACTIVE -> ACKNOWLEDGED and recording metadata."""
        e1 = FenceBreachEvent(track_id=1, breach_count=1)
        alert = alert_engine.process_fence_breach(e1)

        ack_alert = alert_engine.acknowledge(alert.alert_id, acknowledged_by="Officer Sarah", timestamp=1234.5)
        assert ack_alert.status == AlertStatus.ACKNOWLEDGED
        assert ack_alert.acknowledged_by == "Officer Sarah"
        assert ack_alert.acknowledged_at == 1234.5
        assert ack_alert.is_acknowledged is True
        assert ack_alert.is_active is False

        # Verify state in engine matches
        stored = alert_engine.get_alert(alert.alert_id)
        assert stored.status == AlertStatus.ACKNOWLEDGED

    def test_16_resolve_transition(self, alert_engine: AlertEngine):
        """Test transitioning ACTIVE -> RESOLVED and ACKNOWLEDGED -> RESOLVED."""
        e1 = FenceBreachEvent(track_id=1, breach_count=1)
        e2 = LoiteringEvent(track_id=2, loitering_count=1)
        a1 = alert_engine.process_fence_breach(e1)
        a2 = alert_engine.process_loitering(e2)

        # Path 1: ACTIVE -> RESOLVED directly
        r1 = alert_engine.resolve(a1.alert_id, resolved_by="Officer John")
        assert r1.status == AlertStatus.RESOLVED
        assert r1.is_resolved is True
        assert r1.resolved_by == "Officer John"
        assert r1.resolved_at is not None

        # Path 2: ACTIVE -> ACKNOWLEDGED -> RESOLVED
        alert_engine.acknowledge(a2.alert_id, acknowledged_by="Officer John")
        r2 = alert_engine.resolve(a2.alert_id, resolved_by="Officer Mike")
        assert r2.status == AlertStatus.RESOLVED
        assert r2.acknowledged_by == "Officer John"
        assert r2.resolved_by == "Officer Mike"

    def test_17_invalid_state_transitions_raise_exception(self, alert_engine: AlertEngine):
        """Test that invalid backwards or terminal transitions raise InvalidAlertStateTransitionError."""
        e1 = FenceBreachEvent(track_id=1, breach_count=1)
        alert = alert_engine.process_fence_breach(e1)

        # ACKNOWLEDGED -> cannot re-acknowledge
        alert_engine.acknowledge(alert.alert_id)
        with pytest.raises(InvalidAlertStateTransitionError):
            alert_engine.acknowledge(alert.alert_id)

        # RESOLVED -> terminal state
        alert_engine.resolve(alert.alert_id)

        # Cannot resolve again
        with pytest.raises(InvalidAlertStateTransitionError):
            alert_engine.resolve(alert.alert_id)

        # Cannot acknowledge a resolved alert
        with pytest.raises(InvalidAlertStateTransitionError):
            alert_engine.acknowledge(alert.alert_id)

    def test_18_unknown_alert_id_raises_not_found(self, alert_engine: AlertEngine):
        """Test that operations on unknown alert ID raise AlertNotFoundError."""
        with pytest.raises(AlertNotFoundError):
            alert_engine.acknowledge("ALT-UNKNOWN")

        with pytest.raises(AlertNotFoundError):
            alert_engine.resolve("ALT-UNKNOWN")

    def test_19_and_20_reset_and_clear(self, alert_engine: AlertEngine):
        """Test reset and clear methods clear all alerts and deduplication memory."""
        e1 = FenceBreachEvent(track_id=1, breach_count=1)
        e2 = LoiteringEvent(track_id=2, loitering_count=1)
        alert_engine.process_fence_breach(e1)
        alert_engine.process_loitering(e2)
        assert len(alert_engine) == 2

        alert_engine.clear()
        assert len(alert_engine) == 0
        assert alert_engine.get_all_alerts() == []

        # After reset, the same event can be processed again
        a1_again = alert_engine.process_fence_breach(e1)
        assert a1_again is not None
        assert a1_again.alert_id == "ALT-00001"  # counter reset


class TestM8M9IntegrationAndIndependence:
    """Tests 24, 25, 26, 27, 30: Integration with M8 and M9, no source mutation."""

    def test_24_m8_fence_breach_detector_to_m10_integration(self):
        """Test end-to-end integration from M8 detector through M10 AlertEngine."""
        zm = ZoneManager(include_boundary=True)
        zm.create_zone(
            zone_id="perimeter_fence",
            zone_name="Perimeter Virtual Fence",
            zone_type=ZoneType.FENCE,
            polygon=[(100, 100), (300, 100), (300, 300), (100, 300)],
        )
        m8_detector = FenceBreachDetector()
        m10_engine = AlertEngine()

        # Frame 1: OUTSIDE
        obj_f1 = TrackedObject(
            track_id=42, class_id=0, class_name="person", confidence=0.9, x1=10, y1=10, x2=50, y2=50
        )
        zr1 = zm.classify_object(obj_f1)
        m8_detector.update_from_zone_result(zr1, frame_id=1, timestamp=0.1)

        # Frame 2: INSIDE -> generates FenceBreachEvent
        obj_f2 = TrackedObject(
            track_id=42, class_id=0, class_name="person", confidence=0.95, x1=150, y1=150, x2=250, y2=250
        )
        zr2 = zm.classify_object(obj_f2)
        breach_event = m8_detector.update_from_zone_result(zr2, frame_id=2, timestamp=0.2)
        assert breach_event is not None
        assert isinstance(breach_event, FenceBreachEvent)

        # Consume into M10
        alert = m10_engine.process_fence_breach(breach_event)
        assert alert is not None
        assert alert.alert_type == AlertType.FENCE_BREACH
        assert alert.severity == AlertSeverity.CRITICAL
        assert alert.track_id == 42

    def test_25_m9_loitering_detector_to_m10_integration(self):
        """Test end-to-end integration from M9 detector through M10 AlertEngine."""
        ev_mem = EventMemory()
        m9_detector = LoiteringDetector(
            loitering_duration_seconds=1.0, spatial_radius=50.0, min_observations=2
        )
        m10_engine = AlertEngine()

        # Observation 1 at t0
        t0 = datetime(2026, 9, 12, 12, 0, 0)
        obj1 = TrackedObject(
            track_id=88, class_id=0, class_name="person", confidence=0.9, x1=100, y1=100, x2=140, y2=180
        )
        tm1 = ev_mem.update(obj1, frame_time=t0)
        res1 = m9_detector.update_track(tm1, frame_id=1, timestamp=t0)
        assert res1.new_event is None

        # Observation 2 at t0 + 1.5s (within spatial radius, duration exceeds 1.0s threshold)
        t1 = t0 + timedelta(seconds=1.5)
        obj2 = TrackedObject(
            track_id=88, class_id=0, class_name="person", confidence=0.9, x1=102, y1=101, x2=142, y2=181
        )
        tm2 = ev_mem.update(obj2, frame_time=t1)
        res2 = m9_detector.update_track(tm2, frame_id=2, timestamp=t1)
        assert res2.new_event is not None
        assert isinstance(res2.new_event, LoiteringEvent)

        # Consume into M10
        alert = m10_engine.process_loitering(res2.new_event)
        assert alert is not None
        assert alert.alert_type == AlertType.LOITERING
        assert alert.severity == AlertSeverity.HIGH
        assert alert.track_id == 88

    def test_26_m8_and_m9_independence(self):
        """Test that M10 resets or operations do NOT mutate M8 or M9 state."""
        m8_detector = FenceBreachDetector()
        m9_detector = LoiteringDetector(loitering_duration_seconds=1.0)
        m10_engine = AlertEngine()

        ev_mem = EventMemory()
        t0 = datetime(2026, 9, 12, 12, 0, 0)
        obj = TrackedObject(
            track_id=77, class_id=0, class_name="person", confidence=0.9, x1=10, y1=10, x2=50, y2=50
        )
        tm = ev_mem.update(obj, frame_time=t0)

        m8_detector.update_track(track_id=77, fence_inside=True, frame_id=1)
        m9_detector.update_track(tm, frame_id=1, timestamp=t0)

        # Reset M10
        m10_engine.reset()

        # Verify M8 and M9 state remains intact
        assert m8_detector.get_track_state(77) is not None
        assert m9_detector.get_track_state(77) is not None

    def test_27_no_mutation_of_source_events(
        self, alert_engine: AlertEngine, sample_fence_breach_event: FenceBreachEvent
    ):
        """Test that processing an event does not mutate any fields of the source event."""
        orig_dict = {
            "track_id": sample_fence_breach_event.track_id,
            "event_type": sample_fence_breach_event.event_type,
            "frame_id": sample_fence_breach_event.frame_id,
            "breach_count": sample_fence_breach_event.breach_count,
        }
        alert = alert_engine.process_fence_breach(sample_fence_breach_event)
        assert alert is not None
        assert sample_fence_breach_event.track_id == orig_dict["track_id"]
        assert sample_fence_breach_event.event_type == orig_dict["event_type"]
        assert sample_fence_breach_event.frame_id == orig_dict["frame_id"]
        assert sample_fence_breach_event.breach_count == orig_dict["breach_count"]

    def test_30_realistic_event_sequence(self, alert_engine: AlertEngine):
        """Test realistic sequence: breach -> alert -> ack -> loitering -> alert -> resolve all."""
        # 1. Fence breach occurs on Track 10
        fb = FenceBreachEvent(track_id=10, breach_count=1, frame_id=100, timestamp=10.0)
        a_fb = alert_engine.process_fence_breach(fb)
        assert a_fb is not None
        assert a_fb.is_active is True

        # 2. Operator acknowledges breach
        a_fb_ack = alert_engine.acknowledge(a_fb.alert_id, acknowledged_by="Duty Officer")
        assert a_fb_ack.is_acknowledged is True

        # 3. Loitering occurs on Track 15
        loiter = LoiteringEvent(track_id=15, loitering_count=1, duration_seconds=35.0, frame_id=200, timestamp=15.0)
        a_loiter = alert_engine.process_loitering(loiter)
        assert a_loiter is not None
        assert a_loiter.is_active is True

        # 4. Check active alerts
        active_unacked = alert_engine.get_active_alerts(include_acknowledged=False)
        assert len(active_unacked) == 1
        assert active_unacked[0].alert_id == a_loiter.alert_id

        active_all = alert_engine.get_active_alerts(include_acknowledged=True)
        assert len(active_all) == 2

        # 5. Resolve both
        alert_engine.resolve(a_fb.alert_id, resolved_by="Duty Officer")
        alert_engine.resolve(a_loiter.alert_id, resolved_by="Duty Officer")

        # 6. Verify zero active alerts remain
        assert alert_engine.count_active_alerts(include_acknowledged=True) == 0
        all_resolved = alert_engine.filter_alerts(status=AlertStatus.RESOLVED)
        assert len(all_resolved) == 2


class TestEdgeCasesAndValidation:
    """Edge cases, validation, serialization."""

    def test_none_event_raises_validation_error(self, alert_engine: AlertEngine):
        """None event raises AlertValidationError."""
        with pytest.raises(AlertValidationError):
            alert_engine.process_fence_breach(None)

        with pytest.raises(AlertValidationError):
            alert_engine.process_loitering(None)

        with pytest.raises(AlertValidationError):
            alert_engine.process_event(None)

    def test_unsupported_event_type_raises_validation_error(self, alert_engine: AlertEngine):
        """Arbitrary unsupported object raises AlertValidationError."""
        with pytest.raises(AlertValidationError):
            alert_engine.process_event("InvalidStringEvent")

    def test_alert_to_dict_serialization(self, sample_fence_breach_event: FenceBreachEvent):
        """Test JSON-compatible dictionary serialization."""
        engine = AlertEngine()
        alert = engine.process_fence_breach(sample_fence_breach_event)
        data = alert.to_dict()

        assert data["alert_id"] == alert.alert_id
        assert data["track_id"] == 12
        assert data["alert_type"] == "FENCE_BREACH"
        assert data["severity"] == "CRITICAL"
        assert data["status"] == "ACTIVE"
        assert data["center"] == [320.0, 240.0]
        assert data["zone_id"] == "zone_restricted_1"
        assert isinstance(data["message"], str)
