"""WebSocket Pipeline Adapter for IBVAP Module 17.

Provides a clean event-publishing adapter connecting the AI analytics pipeline
(Module 12) with the WebSocket real-time delivery layer without coupling
detection or tracking algorithms to networking code.
"""

import asyncio
import base64
from datetime import datetime, timezone
import logging
from typing import Any, Dict, List, Optional, Union

import numpy as np

from app.schemas.websocket import (
    AlertData,
    CameraStatusData,
    CameraStreamStatus,
    FrameData,
    HeartbeatData,
    StatsData,
    WebSocketMessage,
    WebSocketMessageType,
)
from app.services.websocket_manager import WebSocketConnectionManager, websocket_manager

logger = logging.getLogger("ibvap.websocket_adapter")


def _to_utc_iso(dt: Optional[Union[datetime, float, str]] = None) -> str:
    """Safely convert various timestamp formats to UTC ISO 8601 string."""
    if dt is None:
        return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
    if isinstance(dt, datetime):
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt.astimezone(timezone.utc).isoformat().replace("+00:00", "Z")
    if isinstance(dt, (int, float)):
        return datetime.fromtimestamp(dt, tz=timezone.utc).isoformat().replace("+00:00", "Z")
    return str(dt)


def _encode_frame_to_base64(frame: Union[np.ndarray, bytes, str]) -> str:
    """Convert an image frame (numpy array or raw bytes) to a base64 ASCII string."""
    if isinstance(frame, str):
        return frame

    if isinstance(frame, bytes):
        return base64.b64encode(frame).decode("ascii")

    if isinstance(frame, np.ndarray):
        try:
            import cv2
            success, encoded_img = cv2.imencode(".jpg", frame)
            if success:
                return base64.b64encode(encoded_img.tobytes()).decode("ascii")
        except ImportError:
            pass
        # Fallback if cv2 encoding is unavailable
        return base64.b64encode(frame.tobytes()).decode("ascii")

    raise TypeError(f"Cannot encode frame of type {type(frame)} to base64")


class PipelineWebSocketAdapter:
    """Adapter for publishing AI Pipeline events, frames, and alerts to WebSocket subscribers."""

    def __init__(
        self,
        camera_id: str,
        manager: Optional[WebSocketConnectionManager] = None,
        loop: Optional[asyncio.AbstractEventLoop] = None,
    ) -> None:
        self.camera_id: str = camera_id
        self.manager: WebSocketConnectionManager = manager or websocket_manager
        self.loop: Optional[asyncio.AbstractEventLoop] = loop

    def _dispatch(self, coro) -> None:
        """Helper to schedule coroutine execution regardless of whether caller is sync or async."""
        try:
            current_loop = asyncio.get_running_loop()
            current_loop.create_task(coro)
        except RuntimeError:
            # No running loop in current thread
            target_loop = self.loop
            if target_loop and target_loop.is_running():
                asyncio.run_coroutine_threadsafe(coro, target_loop)
            else:
                asyncio.run(coro)

    # -----------------------------------------------------------------------
    # High-Level Pipeline Result Ingestion
    # -----------------------------------------------------------------------

    async def publish_pipeline_result(
        self,
        result: Any,
        include_frame: bool = False,
        frame_jpeg: Optional[bytes] = None,
        fps: float = 0.0,
    ) -> None:
        """Publish all events, alerts, frames, and statistics generated by an AIPipeline execution."""
        # 1. Dispatch Alerts
        alerts = getattr(result, "alerts", [])
        for alert in alerts:
            await self.publish_alert(alert)

        # 2. Dispatch Video Frame (if requested and available)
        if include_frame:
            frame_to_send = frame_jpeg
            if frame_to_send is None:
                frame_to_send = getattr(result, "processed_frame", None)

            if frame_to_send is not None:
                frame_id = getattr(result, "frame_id", None)
                width = None
                height = None
                if isinstance(frame_to_send, np.ndarray) and frame_to_send.ndim >= 2:
                    height, width = frame_to_send.shape[:2]

                await self.publish_frame(
                    frame=frame_to_send,
                    frame_id=frame_id,
                    width=width,
                    height=height,
                    metadata={"alerts": len(alerts), "objects": len(getattr(result, "tracked_objects", []))},
                )

        # 3. Dispatch Stats
        tracked_objects = getattr(result, "tracked_objects", [])
        connected_clients = self.manager.get_camera_connection_count(self.camera_id)
        stats_data = StatsData(
            active_tracks=len(tracked_objects),
            total_detections=len(tracked_objects),
            active_alerts=len(alerts),
            fps=fps,
            connected_clients=connected_clients,
        )
        await self.publish_stats(stats_data)

    # -----------------------------------------------------------------------
    # Direct Publishing Methods
    # -----------------------------------------------------------------------

    async def publish_alert(self, alert: Any) -> int:
        """Publish a security alert to all subscribers of this camera."""
        if hasattr(alert, "__dict__") and not isinstance(alert, dict):
            # Object from ai_engine.alerts.Alert or similar
            alert_id = getattr(alert, "alert_id", "ALT-001")
            track_id = getattr(alert, "track_id", None)
            alert_type = str(getattr(alert, "alert_type", "SECURITY_ALERT"))
            severity = str(getattr(alert, "severity", "HIGH"))
            status = str(getattr(alert, "status", "ACTIVE"))
            message = getattr(alert, "message", "Security Alert Detected")
            ts = _to_utc_iso(getattr(alert, "timestamp", None))
            zone_info = getattr(alert, "zone_info", None) or getattr(alert, "metadata", None)
            evidence_reference = getattr(alert, "evidence_reference", None)
        elif isinstance(alert, dict):
            alert_id = alert.get("alert_id", "ALT-001")
            track_id = alert.get("track_id")
            alert_type = str(alert.get("alert_type", "SECURITY_ALERT"))
            severity = str(alert.get("severity", "HIGH"))
            status = str(alert.get("status", "ACTIVE"))
            message = str(alert.get("message", "Security Alert Detected"))
            ts = _to_utc_iso(alert.get("timestamp"))
            zone_info = alert.get("zone_info") or alert.get("metadata")
            evidence_reference = alert.get("evidence_reference")
        else:
            raise TypeError(f"Unsupported alert object type: {type(alert)}")

        alert_data = AlertData(
            alert_id=alert_id,
            camera_id=self.camera_id,
            track_id=track_id,
            alert_type=alert_type,
            severity=severity,
            status=status,
            message=message,
            timestamp=ts,
            zone_info=zone_info if isinstance(zone_info, dict) else None,
            evidence_reference=evidence_reference,
        )

        msg = WebSocketMessage(
            type=WebSocketMessageType.ALERT,
            camera_id=self.camera_id,
            data=alert_data.model_dump(),
        )
        return await self.manager.broadcast_to_camera(self.camera_id, msg)

    async def publish_frame(
        self,
        frame: Union[np.ndarray, bytes, str],
        frame_id: Optional[int] = None,
        width: Optional[int] = None,
        height: Optional[int] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> int:
        """Publish an encoded video frame with backpressure protection."""
        encoded_data = _encode_frame_to_base64(frame)

        frame_data = FrameData(
            frame_id=frame_id,
            encoded_data=encoded_data,
            width=width,
            height=height,
            metadata=metadata,
        )

        msg = WebSocketMessage(
            type=WebSocketMessageType.FRAME,
            camera_id=self.camera_id,
            data=frame_data.model_dump(),
        )
        return await self.manager.broadcast_to_camera(self.camera_id, msg)

    async def publish_camera_status(
        self,
        status: Union[CameraStreamStatus, str],
        details: Optional[str] = None,
    ) -> int:
        """Publish an operational camera status transition."""
        status_enum = CameraStreamStatus(status) if isinstance(status, str) else status
        status_data = CameraStatusData(status=status_enum, details=details)

        msg = WebSocketMessage(
            type=WebSocketMessageType.CAMERA_STATUS,
            camera_id=self.camera_id,
            data=status_data.model_dump(),
        )
        return await self.manager.broadcast_to_camera(self.camera_id, msg)

    async def publish_stats(self, stats: Union[StatsData, Dict[str, Any]]) -> int:
        """Publish real-time tracking and performance statistics."""
        if isinstance(stats, dict):
            stats_data = StatsData(**stats)
        elif isinstance(stats, StatsData):
            stats_data = stats
        else:
            raise TypeError(f"Unsupported stats type: {type(stats)}")

        msg = WebSocketMessage(
            type=WebSocketMessageType.STATS,
            camera_id=self.camera_id,
            data=stats_data.model_dump(),
        )
        return await self.manager.broadcast_to_camera(self.camera_id, msg)

    async def publish_heartbeat(self, reply: Optional[str] = None) -> int:
        """Publish an application-level heartbeat message."""
        hb_data = HeartbeatData(reply=reply)
        msg = WebSocketMessage(
            type=WebSocketMessageType.HEARTBEAT,
            camera_id=self.camera_id,
            data=hb_data.model_dump(),
        )
        return await self.manager.broadcast_to_camera(self.camera_id, msg)
